---
frequency: 10
rpi:
  clock_pin: 11
  data_pin: 10
stations:
- code: KSAN
  led: 0
  name: SAN DIEGO INTL
- code: KNYL
  led: 1
  name: YUMA MCAS/YUMA INTL
- code: KPHX
  led: 2
  name: PHOENIX SKY HARBOR INTL
- code: KTUS
  led: 3
  name: TUCSON INTL
- code: KDMN
  led: 4
  name: DEMING MUNI
- code: KELP
  led: 5
  name: EL PASO INTL
- code: KROW
  led: 6
  name: ROSWELL INTL AIR CENTER
- code: KABQ
  led: 7
  name: ALBUQUERQUE INTL SUNPORT
- code: KFMN
  led: 8
  name: FOUR CORNERS RGNL
- code: KASE
  led: 9
  name: ASPEN-PITKIN CO/SARDY FIELD
- code: KCYS
  led: 10
  name: CHEYENNE RGNL/JERRY OLSON FIELD
- code: KDEN
  led: 11
  name: DENVER INTL
- code: KGLD
  led: 12
  name: RENNER FLD /GOODLAND MUNI/
- code: KHQG
  led: 13
  name: HUGOTON MUNI
- code: KAMA
  led: 14
  name: RICK HUSBAND AMARILLO INTL
- code: KLBB
  led: 15
  name: LUBBOCK PRESTON SMITH INTL
- code: KMAF
  led: 16
  name: MIDLAND INTL AIR AND SPACE PORT
- code: KFST
  led: 17
  name: FORT STOCKTON-PECOS COUNTY
- code: KSJT
  led: 18
  name: SAN ANGELO RGNL/MATHIS FIELD
- code: KDRT
  led: 19
  name: DEL RIO INTL
- code: KLRD
  led: 20
  name: LAREDO INTL
- code: KCRP
  led: 21
  name: CORPUS CHRISTI INTL
- code: KAUS
  led: 22
  name: AUSTIN-BERGSTROM INTL
- code: KIAH
  led: 23
  name: GEORGE BUSH INTERCONTINENTAL/HOUSTON
- code: KLCH
  led: 24
  name: LAKE CHARLES RGNL
- code: KSHV
  led: 25
  name: SHREVEPORT RGNL
- code: KLIT
  led: 26
  name: BILL AND HILLARY CLINTON NATIONAL/ADAMS FIELD
- code: KMLU
  led: 27
  name: MONROE RGNL
- code: KLFT
  led: 28
  name: LAFAYETTE RGNL/PAUL FOURNET FIELD
- code: KMSY
  led: 29
  name: LOUIS ARMSTRONG NEW ORLEANS INTL
- code: KGPT
  led: 30
  name: GULFPORT-BILOXI INTL
- code: KJAN
  led: 31
  name: JACKSON-MEDGAR WILEY EVERS INTL
- code: KGWO
  led: 32
  name: GREENWOOD-LEFLORE
- code: KMEM
  led: 33
  name: MEMPHIS INTL
- code: KPAH
  led: 34
  name: BARKLEY RGNL
- code: KSTL
  led: 35
  name: ST LOUIS LAMBERT INTL
- code: KBMI
  led: 36
  name: CENTRAL IL RGNL ARPT AT BLOOMINGTON-NORMAL
- code: KIND
  led: 37
  name: INDIANAPOLIS INTL
- code: KLEX
  led: 38
  name: BLUE GRASS
- code: KBNA
  led: 39
  name: NASHVILLE INTL
- code: KBHM
  led: 40
  name: BIRMINGHAM-SHUTTLESWORTH INTL
- code: KMGM
  led: 41
  name: MONTGOMERY RGNL (DANNELLY FIELD)
- code: KPNS
  led: 42
  name: PENSACOLA INTL
- code: KECP
  led: 43
  name: NORTHWEST FLORIDA BEACHES INTL
- code: KTLH
  led: 44
  name: TALLAHASSEE INTL
- code: KOCF
  led: 45
  name: OCALA INTL-JIM TAYLOR FIELD
- code: KTPA
  led: 46
  name: TAMPA INTL
- code: KFMY
  led: 47
  name: PAGE FIELD
- code: KEYW
  led: 48
  name: KEY WEST INTL
- code: KMIA
  led: 49
  name: MIAMI INTL
- code: MYNN
  led: 50
  name: LYNDEN PINDLING INTL
- code: MYGF
  led: 51
  name: GRAND BAHAMA INTL
- code: KPBI
  led: 52
  name: PALM BEACH INTL
- code: KMCO
  led: 53
  name: ORLANDO INTL
- code: KJAX
  led: 54
  name: JACKSONVILLE INTL
- code: KABY
  led: 55
  name: SOUTHWEST GEORGIA RGNL
- code: KATL
  led: 56
  name: HARTSFIELD - JACKSON ATLANTA INTL
- code: KCHA
  led: 57
  name: LOVELL FIELD
- code: KTYS
  led: 58
  name: MC GHEE TYSON
- code: KCLT
  led: 59
  name: CHARLOTTE/DOUGLAS INTL
- code: KAGS
  led: 60
  name: AUGUSTA RGNL AT BUSH FIELD
- code: KSAV
  led: 61
  name: SAVANNAH/HILTON HEAD INTL
- code: KCHS
  led: 62
  name: CHARLESTON AFB/INTL
- code: KMYR
  led: 63
  name: MYRTLE BEACH INTL
- code: KEWN
  led: 64
  name: COASTAL CAROLINA REGIONAL
- code: KRDU
  led: 65
  name: RALEIGH-DURHAM INTL
- code: KORF
  led: 66
  name: NORFOLK INTL
- code: KIAD
  led: 67
  name: WASHINGTON DULLES INTL
- code: KDOV
  led: 68
  name: DOVER AFB
- code: KPHL
  led: 69
  name: PHILADELPHIA INTL
- code: KEWR
  led: 70
  name: NEWARK LIBERTY INTL
- code: KJFK
  led: 71
  name: JOHN F KENNEDY INTL
- code: KHPN
  led: 72
  name: WESTCHESTER COUNTY
- code: KISP
  led: 73
  name: LONG ISLAND MAC ARTHUR
- code: KGON
  led: 74
  name: GROTON-NEW LONDON
- code: KHFD
  led: 75
  name: HARTFORD-BRAINARD
- code: KMVY
  led: 76
  name: MARTHA'S VINEYARD
- code: KBOS
  led: 77
  name: GENERAL EDWARD LAWRENCE LOGAN INTL
- code: KPWM
  led: 78
  name: PORTLAND INTL JETPORT
- code: KBGR
  led: 79
  name: BANGOR INTL
- code: KLEB
  led: 80
  name: LEBANON MUNI
- code: KBTV
  led: 81
  name: BURLINGTON INTL
- code: KALB
  led: 82
  name: ALBANY INTL
- code: KSWF
  led: 83
  name: NEW YORK STEWART INTL
- code: KAVP
  led: 84
  name: WILKES-BARRE/SCRANTON INTL
- code: KSYR
  led: 85
  name: SYRACUSE HANCOCK INTL
- code: KBUF
  led: 86
  name: BUFFALO NIAGARA INTL
- code: KUNV
  led: 87
  name: UNIVERSITY PARK
- code: KPIT
  led: 88
  name: PITTSBURGH INTL
- code: KCKB
  led: 89
  name: NORTH CENTRAL WEST VIRGINIA
- code: KROA
  led: 90
  name: ROANOKE-BLACKSBURG RGNL/WOODRUM FIELD
- code: KCRW
  led: 91
  name: YEAGER
- code: KCVG
  led: 92
  name: CINCINNATI/NORTHERN KENTUCKY INTL
- code: KCMH
  led: 93
  name: JOHN GLENN COLUMBUS INTL
- code: KCLE
  led: 94
  name: CLEVELAND-HOPKINS INTL
- code: KDTW
  led: 95
  name: DETROIT METROPOLITAN WAYNE COUNTY
- code: KMKG
  led: 96
  name: MUSKEGON COUNTY
- code: KORD
  led: 97
  name: CHICAGO O'HARE INTL
- code: KGRB
  led: 98
  name: GREEN BAY-AUSTIN STRAUBEL INTL
- code: KEAU
  led: 99
  name: CHIPPEWA VALLEY RGNL
- code: KDLH
  led: 100
  name: DULUTH INTL
- code: KMSP
  led: 101
  name: MINNEAPOLIS-ST PAUL INTL/WOLD-CHAMBERLAIN
- code: KCMY
  led: 102
  name: SPARTA/FORT MC COY
- code: KMLI
  led: 103
  name: QUAD CITY INTL
- code: KDSM
  led: 104
  name: DES MOINES INTL
- code: KMCI
  led: 105
  name: KANSAS CITY INTL
- code: KSGF
  led: 106
  name: SPRINGFIELD-BRANSON NATIONAL
- code: KFYV
  led: 107
  name: DRAKE FIELD
- code: KTXK
  led: 108
  name: TEXARKANA RGNL-WEBB FIELD
- code: KDFW
  led: 109
  name: DALLAS-FORT WORTH INTL
- code: KOKC
  led: 110
  name: WILL ROGERS WORLD
- code: KTUL
  led: 111
  name: TULSA INTL
- code: KICT
  led: 112
  name: WICHITA DWIGHT D EISENHOWER NATIONAL
- code: KSLN
  led: 113
  name: SALINA RGNL
- code: KGRI
  led: 114
  name: CENTRAL NEBRASKA RGNL
- code: KOMA
  led: 115
  name: EPPLEY AIRFIELD
- code: KFSD
  led: 116
  name: JOE FOSS FIELD
- code: KMOX
  led: 117
  name: MORRIS MUNI - CHARLIE SCHMIDT FLD
- code: KFAR
  led: 118
  name: HECTOR INTL
- code: KGFK
  led: 119
  name: GRAND FORKS INTL
- code: KMOT
  led: 120
  name: MINOT INTL
- code: KBWW
  led: 121
  name: BOWMAN RGNL
- code: KRAP
  led: 122
  name: RAPID CITY RGNL
- code: KGCC
  led: 123
  name: GILLETTE-CAMPBELL COUNTY
- code: KBIL
  led: 124
  name: BILLINGS LOGAN INTL
- code: KHLN
  led: 125
  name: HELENA RGNL
- code: KGPI
  led: 126
  name: GLACIER PARK INTL
- code: KGEG
  led: 127
  name: SPOKANE INTL
- code: KYKM
  led: 128
  name: YAKIMA AIR TERMINAL/MCALLISTER FIELD
- code: KSEA
  led: 129
  name: SEATTLE-TACOMA INTL
- code: KPDX
  led: 130
  name: PORTLAND INTL
- code: KEUG
  led: 131
  name: MAHLON SWEET FIELD
- code: KMFR
  led: 132
  name: ROGUE VALLEY INTL - MEDFORD
- code: KRDD
  led: 133
  name: REDDING MUNI
- code: KSAC
  led: 134
  name: SACRAMENTO EXECUTIVE
- code: KSFO
  led: 135
  name: SAN FRANCISCO INTL
- code: KFAT
  led: 136
  name: FRESNO YOSEMITE INTL
- code: KSBP
  led: 137
  name: SAN LUIS COUNTY RGNL
- code: KLAX
  led: 138
  name: LOS ANGELES INTL
- code: KPSP
  led: 139
  name: PALM SPRINGS INTL
- code: KLAS
  led: 140
  name: MC CARRAN INTL
- code: KGCN
  led: 141
  name: GRAND CANYON NATIONAL PARK
- code: KMLF
  led: 142
  name: MILFORD MUNI/BEN AND JUDY BRISCOE FIELD
- code: KSLC
  led: 143
  name: SALT LAKE CITY INTL
- code: KPIH
  led: 144
  name: POCATELLO RGNL
- code: KJAC
  led: 145
  name: JACKSON HOLE
- code: KSUN
  led: 146
  name: FRIEDMAN MEMORIAL
- code: KTWF
  led: 147
  name: JOSLIN FIELD - MAGIC VALLEY RGNL
- code: KBAM
  led: 148
  name: BATTLE MOUNTAIN
  neighbors:
   - KRNO
   - KTWF
- code: KRNO
  led: 149
  name: RENO/TAHOE INTL
