controller: "rpi"
leds: 50
database: sqlite:////data/ledvfrmap.db
color_picker: "category"
rpi:
  gpio_mode: "BCM"
  data_pin: 10
  clock_pin: 11
  button:
    pin: 4
    pull: "DOWN"
    long_press_time: 5000
    bounce_time: 500
stations:
  # Maine
  - code: KPQI
    name: Presque Isle International Airport
    led: 1
  - code: KBGR
    name: Bangor International Airport
    led: 2
  - code: KPWM
    name: Portland International Jetport
    led: 3
  # Vermont
  - code: KBTV
    name: Burlington International Airport
    led: 4
  # New Hampshire
  - code: KLEB
    name: Lebanon Municipal Airport
    led: 5
  - code: KMHT
    name: Manchester-Boston Regional Airport
    led: 6
  - code: KPSM
    name: Portsmouth International Airport at Pease
    led: 7
  # Massachusetts
  - code: KBOS
    name: Gen. Edward Lawrence Logan International Airport
    led: 8
  - code: KACK
    name: Nantucket Memorial Airport
    led: 9
  - code: KMVY
    name: Martha\'s Vineyard Airport
    led: 10
  # Rhode Island
  - code: KPVD
    name: Theodore Francis Green State Airport
    led: 11
  - code: KBID
    name: Block Island State Airport
    led: 12
  # Connecticut
  - code: KGON
    name: Groton-New London Airport
    led: 13
  - code: KBDL
    name: Bradley International Airport
    led: 14
  - code: KHFD
    name: Hartford-Brainard Airport
    led: 15
  - code: KDXR
    name: Danbury Municipal Airport
    led: 16
  # New York
  - code: KISP
    name: Long Island MacArthur Airport
    led: 17
  - code: KFRG
    name: Republic Airport
    led: 18
  - code: KJFK
    name: John F. Kennedy International Airport
    led: 19
  - code: KLGA
    name: LaGuardia Airport
    led: 20
  - code: KHPN
    name: Westchester County Airport
    led: 21
  - code: KSWF
    name: Stewart International Airport
    led: 22
  - code: KALB
    name: Albany International Airport
    led: 23
  - code: KOGS
    name: Ogdensburg International Airport
    led: 24
  - code: KSYR
    name: Syracuse Hancock International Airport
    led: 25
  - code: KROC
    name: Greater Rochester International Airport
    led: 26
  - code: KBUF
    name: Buffalo Niagra International Airport
    led: 27
  - code: KIAG
    name: Niagra Falls International Airport
    led: 28
  # Pennsylvania
  - code: KERI
    name: Erie International Airport
    led: 29
  - code: KPIT
    name: Pittsburgh International Airport
    led: 30
  - code: KUNV
    name: University Park Airport
    led: 31
  - code: KMDT
    name: Harrisburg International Airport
    led: 32
  - code: KAVP
    name: Wilkes-Barre/Scranton International Airport
    led: 33
  - code: KPHL
    name: Philadelphia International Airport
    led: 34
  # New Jersey
  - code: KEWR
    name: Newark Liberty International Airport
    led: 35 
  - code: KACY
    name: Atlantic City International Airport
    led: 36
  # Delaware
  # Maryland
  - code: KADW
    name: Andrews Air Force Base
    led: 37
  - code: KBWI
    name: Baltimore-Washington International Airport
    led: 38
  # Washington D.C.
  # Michigan
  - code: KDTW
    name: Detroit Metropolitan Wayne County Airport
    led: 39
  # Minnesota
  - code: KMSP
    name: Minneapolis-Saint Paul International Airport
    led: 40
  # Missouri
  - code: KMCI
    name: Kansas City International Airport
    led: 41
  - code: KSTL
    name: Lambert-St. Louis International Airport
    led: 42
  # North Carolina
  - code: KCLT
    name: Charlotte Douglas International Airport
    led: 43
  # Ohio
  - code: KCLE
    name: Cleveland Hopkins International Airport
    led: 44
  # Texas
  - code: KDFW 
    name: Dallas/Fort Worth International Airport
    led: 45
  - code: KHOU
    name: William P. Hobby Airport
    led: 46
  - code: KIAH
    name: George Bush Intercontinental Airport
    led: 47
  # Utah
  - code: KSLC
    name: Salt Lake City International Airport
    led: 48
  # Virginia
  - code: KDCA
    name: Ronald Reagan Washington National Airport
    led: 49
  - code: KIAD
    name: Washington Dulles International Airport
    led: 0
  # Washington
  - code: KSEA
    name: Seattle-Tacoma International Airport
    led: 
  # Nevada
  - code: KLAS
    name: Las Vegas McCarran
    led: 
  # Georgia
  - code: KATL
    name: Hartsfield-Jackson Atlanta International Airport
    led:
  # Hawaii
  - code: KHNL
    name: Honolulu International Airport
    led:
  # Illinois
  - code: KORD
    name: O\'Hare International Airport
    led:
  # Kentucky:
  - code: KCVG
    name: Cincinnati/Northern Kentucky International Airport
    led:
  # Louisiana
  - code: KMSY
    name: Louis Armstrong New Orleans International Airport
    led:
  # Tennessee
  - code: KTYS
    name: Tyson McGee
    led:
  - code: KMEM
    name: Memphis International Airport
    led:
  # Florida
  - code: KMCO
    name: Orlando International Airport
    led: 
  - code: KMIA
    name: Miami International
    led: 
  - code: KTPA
    name: Tampa International Airport
    led:
  # Arizona
  - code: KPHX
    name: Phoenix Sky Harbor International Airport
    led:
  # California
  - code: KSFO
    name: San Francisco
    led: 
  - code: KLAX
    name: Los Angeles International
    led: 
  - code: KNKX
    name: Marine Corps Air Station Miramar
    led:
  - code: KSAN
    name: San Diego International Airport
    led:
  # Stub
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
  - code:
    name:
    led:
