#!/usr/bin/env python
import ledvfrmap.map
from pkg_resources import resource_filename
import logging
import os
import signal
import sys
from flask import Flask

aviation_map = None
app = Flask(__name__)


@app.route("/map/off")
def map_off():
    log = logging.getLogger(__name__)
    log.info("Request to turn map off")
    aviation_map.off()
    return "OFF"


@app.route("/map/on")
def map_on():
    log = logging.getLogger(__name__)
    log.info("Request to turn map on")
    aviation_map.on()
    return "ON"


def terminate(signal_number, frame):
    log = logging.getLogger(__name__)
    log.info(f"Received signal {signal_number} at {frame}")

    if aviation_map:
        aviation_map.stop()
    
    sys.exit()


if __name__ == '__main__':
    signal.signal(signal.SIGTERM, terminate)
    import argparse

    logger = logging.getLogger(__name__)

    parser = argparse.ArgumentParser(description="LED VFR Map")
    parser.add_argument('-c', '--config', type=str, dest='config',
                        default=resource_filename('ledvfrmap', 'config.yml'),
                        help="Configuration file")
    parser.add_argument('-v', '--verbose', action='store_const', const=True,
                        dest='verbose', default=False,
                        help="Show more verbose logging output")
    parser.add_argument('-d', '--debug', action='store_const', const=True,
                        dest='debug', default=False,
                        help="Run Flask server in debug mode")
    parser.add_argument('-p', '--port', type=int, default=9999,
                        help='Port for web server to listen on')
    args = parser.parse_args()

    logfmt = "[%(levelname)s %(asctime)s %(module)s %(threadName)s] %(message)s"
    level = logging.INFO

    if args.verbose:
        level = logging.DEBUG

    logging.basicConfig(format=logfmt, level=level)

    if not os.path.exists(args.config):
        logger.error("Config file {} does not exist".format(args.config))
        exit(1)

    aviation_map = ledvfrmap.map.LedMap(args.config)
    app.run(debug=args.debug, port=9999, host='0.0.0.0')
    
    aviation_map.stop()
